### ISSUE TITLE
Occasional errors on script exit

### ISSUE THREAD

**Issue by greg-draganfly** [Parrot-Developers/sequoia-ptpy#1]
Trigger script (and I believe others) occasionally exit with an error.  The script executes properly, but a nasty error appears.  Sample output:

greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "build/bdist.linux-x86_64/egg/ptpy/transports/usb.py", line 380, in __poll_events
  File "build/bdist.linux-x86_64/egg/ptpy/transports/usb.py", line 255, in __recv
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'core'
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ python trigger.py 
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "build/bdist.linux-x86_64/egg/ptpy/transports/usb.py", line 380, in __poll_events
  File "build/bdist.linux-x86_64/egg/ptpy/transports/usb.py", line 255, in __recv
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'core'
greg@ubuntu:~/micasense/sequoia-ptpy/examples$ 
 
Raspberry pi:
 
pi@raspberrypi:~/sequoia-ptpy/examples $ python trigger.py
pi@raspberrypi:~/sequoia-ptpy/examples $ python trigger.py
pi@raspberrypi:~/sequoia-ptpy/examples $ python trigger.py
Unhandled exception in thread started by <bound method Thread.__bootstrap of <Thread(Thread-2, stopped daemon 1976824928)>>
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    pi@raspberrypi:~/sequoia-ptpy/examples $ python trigger.py
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "build/bdist.linux-armv7l/egg/ptpy/transports/usb.py", line 380, in __poll_events
  File "build/bdist.linux-armv7l/egg/ptpy/transports/usb.py", line 255, in __recv
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'core'
pi@raspberrypi:~/sequoia-ptpy/examples $ python trigger.py
Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "build/bdist.linux-armv7l/egg/ptpy/transports/usb.py", line 380, in __poll_events
  File "build/bdist.linux-armv7l/egg/ptpy/transports/usb.py", line 255, in __recv
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'core'

**Comment by domenzain** [comment]
This was still a problem in certain platforms where exit of main thread would happen before other threads realised the main one is no longer alive.
There is a further workaround implemented in 9bd5bcf.
