### ISSUE TITLE
requirements.txt missing from Pypi distribution

### ISSUE THREAD

**Issue by NiklasRosenstein** [Parrot-Developers/sequoia-ptpy#16]
Installing via Pip from Pypi yields

```
Processing /home/niklas/Downloads/ptpy-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/pip/download.py", line 421, in get_file_content
        with open(url, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-tycta6yg-build/setup.py", line 11, in <module>
        for r in parse_requirements('requirements.txt', session=False)
      File "/tmp/pip-tycta6yg-build/setup.py", line 10, in <listcomp>
        str(r.req)
      File "/usr/local/lib/python3.5/dist-packages/pip/req/req_file.py", line 84, in parse_requirements
        filename, comes_from=comes_from, session=session
      File "/usr/local/lib/python3.5/dist-packages/pip/download.py", line 425, in get_file_content
        'Could not open requirements file: %s' % str(exc)
    pip.exceptions.InstallationError: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by NiklasRosenstein** [comment]
Also missing are `tests/requirements.txt` and `README.md`

**Comment by domenzain** [comment]
Thank you for the report.
I've tagged and uploaded a new version.

I'll close this, but if there's trouble don't hesitate to report back.
