### ISSUE TITLE
No TCP_QUICKACK under OS X

### ISSUE THREAD

**Issue by jstarsk** [Parrot-Developers/sequoia-ptpy#17]
Hello. I will want use the PTPy library to comunicat the parrot sequoia camera by IP.
but i having a error in my code.

E 19 ptpy.ptp[MainThread:recv:801] 'module' object has no attribute 'TCP_QUICKACK'
Traceback (most recent call last):
  File "/Users/starsky/StealingFired/nero-sequoia/trigger.py", line 11, in <module>
    main()
  File "/Users/starsky/StealingFired/nero-sequoia/trigger.py", line 6, in main
    NEROSequoia.trigger_camera_wifi()
  File "/Users/starsky/StealingFired/nero-sequoia/NEROSequoia.py", line 23, in trigger_camera_wifi
    c = PTPy(transport=IPTransport, device='197.168.47.1')
  File "build/bdist.macosx-10.12-x86_64/egg/ptpy/__init__.py", line 114, in __new__
  File "build/bdist.macosx-10.12-x86_64/egg/ptpy/ptp.py", line 953, in get_device_info
  File "build/bdist.macosx-10.12-x86_64/egg/ptpy/ptp.py", line 802, in recv
AttributeError: 'module' object has no attribute 'TCP_QUICKACK'

**Comment by domenzain** [comment]
Thanks for the report.
This is explicitly taken care of in 2526404.

Please have a look and report back if things are not working.
