### ISSUE TITLE
unable to connect over ptp ip: 'str' object is not callable

### ISSUE THREAD

**Issue by dvdhpkns** [Parrot-Developers/sequoia-ptpy#18]
Trying to connect to my camera over ptp ip and receiving the following error:

```
E 7967 ptpy.ptp[MainThread:recv:801] 'str' object is not callable
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/davidhopkins/Code/wifi/sequoia-ptpy/examples/download_all_images.py", line 6, in <module>
    camera = ptpy.PTPy(transport=IPTransport, device='192.168.1.8', extension=Canon)
  File "/Users/davidhopkins/Code/wifi/sequoia-ptpy/ptpy/__init__.py", line 135, in __new__
    instance._obtain_the_knowledge()
  File "/Users/davidhopkins/Code/wifi/sequoia-ptpy/ptpy/ptp.py", line 857, in _obtain_the_knowledge
    self.__device_info = self.get_device_info()
  File "/Users/davidhopkins/Code/wifi/sequoia-ptpy/ptpy/ptp.py", line 953, in get_device_info
    response = self.recv(ptp)
  File "/Users/davidhopkins/Code/wifi/sequoia-ptpy/ptpy/ptp.py", line 802, in recv
    raise e
TypeError: 'str' object is not callable
```

I am using the following command: 
`camera = ptpy.PTPy(transport=IPTransport, device='192.168.1.8')`

My camera is a Canon 6D, I have been able to connect over wifi using ptp ip with other libraries such as gphoto2. Let me know if there is any other information I can provide. Thanks!

**Comment by domenzain** [comment]
Hi there,

The problem mentioned is solved in master.
But it will definitely have been transformed into a different issue and the IP transport needs a bunch of testing.

If you could say how you manage to connect successfully to your 6D that would be useful. That is, which camera settings do you use and which commands do you execute?

Thanks!
