### ISSUE TITLE
usb.core.USBError: [Errno 110] Operation timed out

### ISSUE THREAD

**Issue by WIsbrecht** [Parrot-Developers/sequoia-ptpy#23]
Hi,

when i tried the print_device_info example with my Sony a58 over usb i got the following error:
I don't know if its a bug with your library or pyusb/libusb in combination with my OS (Kubuntu 18.04)

```
export PYUSB_DEBUG=debug
export PTPY_DEBUG=1
python print_device_info.py > print_device_info.log 2>&1
```
print_device_info.log:
```
D 22 ptpy[MainThread:__new__:99] New PTPy
D 22 ptpy[MainThread:__new__:101] Determining available transports
D 22 ptpy.ptp[MainThread:__init__:705] Init PTP
D 22 ptpy.transports.usb[MainThread:__init__:72] Init USB
D 23 ptpy.ptp[MainThread:_set_endian:629] Set PTP endianness
D 23 ptpy.transports.usb[MainThread:__init__:77] No device provided, probing all USB devices.
2018-04-30 15:21:48,310 DEBUG:usb.backend.libusb1:_LibUSB.__init__(<CDLL 'libusb-1.0.so.0', handle 557aabf58050 at 0x7f9df861b0f0>)
2018-04-30 15:21:48,313 INFO:usb.core:find(): using backend "usb.backend.libusb1"
2018-04-30 15:21:48,314 DEBUG:usb.backend.libusb1:_LibUSB.enumerate_devices()
2018-04-30 15:21:48,314 DEBUG:usb.backend.libusb1:_LibUSB.get_device_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>)
2018-04-30 15:21:48,314 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,315 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 1, 0, 0, 0)
2018-04-30 15:21:48,316 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,316 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,316 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 2, 0, 0, 0)
2018-04-30 15:21:48,316 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,316 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
D 50 ptpy.transports.usb[MainThread:__setup_device:205] Found <ENDPOINT 0x81: Bulk IN>
D 50 ptpy.transports.usb[MainThread:__setup_device:206] Found <ENDPOINT 0x2: Bulk OUT>
D 50 ptpy.transports.usb[MainThread:__setup_device:207] Found <ENDPOINT 0x83: Interrupt IN>
2018-04-30 15:21:48,316 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>)
2018-04-30 15:21:48,451 DEBUG:usb.backend.libusb1:_LibUSB.ctrl_transfer(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 128, 6, 768, 0, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:48,453 DEBUG:usb.backend.libusb1:_LibUSB.ctrl_transfer(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 128, 6, 769, 1033, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:48,456 DEBUG:usb.backend.libusb1:_LibUSB.ctrl_transfer(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 128, 6, 770, 1033, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:48,457 DEBUG:usb.backend.libusb1:_LibUSB.ctrl_transfer(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 128, 6, 771, 1033, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:48,460 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,460 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,460 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,460 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0, 0)
2018-04-30 15:21:48,460 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 1, 0, 0, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 2, 0, 0, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,461 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,462 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 1, 0)
2018-04-30 15:21:48,462 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
D 196 ptpy.transports.usb[MainThread:__available_cameras:115] Found USB PTP device DEVICE ID 054c:0737 on Bus 002 Address 010 =================
 bLength                :   0x12 (18 bytes)
 bDescriptorType        :    0x1 Device
 bcdUSB                 :  0x200 USB 2.0
 bDeviceClass           :    0x0 Specified at interface
 bDeviceSubClass        :    0x0
 bDeviceProtocol        :    0x0
 bMaxPacketSize0        :   0x40 (64 bytes)
 idVendor               : 0x054c
 idProduct              : 0x0737
 bcdDevice              :  0x200 Device 2.0
 iManufacturer          :    0x1 Sony
 iProduct               :    0x2 SLT-A58
 iSerialNumber          :    0x3 597C70442A3D
 bNumConfigurations     :    0x1
  CONFIGURATION 1: 2 mA ====================================
   bLength              :    0x9 (9 bytes)
   bDescriptorType      :    0x2 Configuration
   wTotalLength         :   0x27 (39 bytes)
   bNumInterfaces       :    0x1
   bConfigurationValue  :    0x1
   iConfiguration       :    0x0 
   bmAttributes         :   0xc0 Self Powered
   bMaxPower            :    0x1 (2 mA)
    INTERFACE 0: Image =====================================
     bLength            :    0x9 (9 bytes)
     bDescriptorType    :    0x4 Interface
     bInterfaceNumber   :    0x0
     bAlternateSetting  :    0x0
     bNumEndpoints      :    0x3
     bInterfaceClass    :    0x6 Image
     bInterfaceSubClass :    0x1
     bInterfaceProtocol :    0x1
     iInterface         :    0x0 
      ENDPOINT 0x81: Bulk IN ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x81 IN
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x2: Bulk OUT ===============================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :    0x2 OUT
       bmAttributes     :    0x2 Bulk
       wMaxPacketSize   :  0x200 (512 bytes)
       bInterval        :    0x0
      ENDPOINT 0x83: Interrupt IN ==========================
       bLength          :    0x7 (7 bytes)
       bDescriptorType  :    0x5 Endpoint
       bEndpointAddress :   0x83 IN
       bmAttributes     :    0x3 Interrupt
       wMaxPacketSize   :   0x20 (32 bytes)
       bInterval        :    0x7
2018-04-30 15:21:48,462 DEBUG:usb.backend.libusb1:_LibUSB.is_kernel_driver_active(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 0)
D 196 ptpy.transports.usb[MainThread:__acquire_camera:143] Claiming <DEVICE ID 054c:0737 on Bus 002 Address 010>
2018-04-30 15:21:48,463 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 0)
2018-04-30 15:21:48,463 DEBUG:usb.backend.libusb1:_LibUSB.release_interface(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>, 0)
2018-04-30 15:21:48,463 DEBUG:usb.backend.libusb1:_LibUSB.reset_device(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>)
2018-04-30 15:21:48,661 DEBUG:usb.backend.libusb1:_LibUSB.close_device(<usb.backend.libusb1._DeviceHandle object at 0x7f9df6693da0>)
2018-04-30 15:21:48,662 DEBUG:usb.backend.libusb1:_LibUSB.open_device(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>)
D 396 ptpy.transports.usb[MainThread:recv:480] RECV GetDeviceInfo
2018-04-30 15:21:48,663 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>)
2018-04-30 15:21:48,663 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,663 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,663 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 1, 0, 0, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 2, 0, 0, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,664 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,665 DEBUG:usb.backend.libusb1:_LibUSB.claim_interface(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 0)
2018-04-30 15:21:48,665 DEBUG:usb.backend.libusb1:_LibUSB.intr_read(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 131, 0, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:48,665 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,665 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,665 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,666 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0, 0)
2018-04-30 15:21:48,666 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,666 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,666 DEBUG:usb.backend.libusb1:_LibUSB.get_endpoint_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 1, 0, 0, 0)
2018-04-30 15:21:48,667 DEBUG:usb.backend.libusb1:_LibUSB.get_interface_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0, 0, 0)
2018-04-30 15:21:48,667 DEBUG:usb.backend.libusb1:_LibUSB.get_configuration_descriptor(<usb.backend.libusb1._Device object at 0x7f9dfb5a1320>, 0)
2018-04-30 15:21:48,667 DEBUG:usb.backend.libusb1:_LibUSB.bulk_write(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 2, 0, array('B', [12, 0, 0, 0, 1, 0, 1, 16, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:49,671 DEBUG:usb.backend.libusb1:_LibUSB.intr_read(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 131, 0, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:49,672 DEBUG:usb.backend.libusb1:_LibUSB.bulk_write(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 2, 0, array('B', [12, 0, 0, 0, 1, 0, 1, 16, 0, 0, 0, 0]), 1000)
2018-04-30 15:21:50,679 DEBUG:usb.backend.libusb1:_LibUSB.intr_read(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 131, 0, array('B', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), 1000)
E 2413 ptpy.ptp[MainThread:recv:801] [Errno 110] Operation timed out
Traceback (most recent call last):
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/transports/usb.py", line 402, in __send
    ep.write(transaction)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/core.py", line 948, in write
    self.__get_timeout(timeout)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/_debug.py", line 60, in do_trace
    return f(*args, **named_args)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/backend/libusb1.py", line 824, in bulk_write
    timeout)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/backend/libusb1.py", line 920, in __write
    _check(retval)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "print_device_info.py", line 4, in <module>
    camera = ptpy.PTPy()
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/__init__.py", line 114, in __new__
    device_info = plain_camera.get_device_info()
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/ptp.py", line 953, in get_device_info
    response = self.recv(ptp)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/ptp.py", line 802, in recv
    raise e
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/ptp.py", line 799, in recv
    return super(PTP, self).recv(ptp_container)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/transports/usb.py", line 483, in recv
    self.__send_request(ptp_container)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/transports/usb.py", line 430, in __send_request
    self.__send(ptp)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/ptpy/transports/usb.py", line 411, in __send
    ep.write(transaction)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/core.py", line 948, in write
    self.__get_timeout(timeout)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/_debug.py", line 60, in do_trace
    return f(*args, **named_args)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/backend/libusb1.py", line 824, in bulk_write
    timeout)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/backend/libusb1.py", line 920, in __write
    _check(retval)
  File "/home/waldi/.pyenv/versions/photobox/lib/python3.6/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 110] Operation timed out
D 3417 ptpy.transports.usb[MainThread:_shutdown:159] Shutdown request
D 3417 ptpy.transports.usb[MainThread:_shutdown:169] Release <DEVICE ID 054c:0737 on Bus 002 Address 010>
2018-04-30 15:21:51,684 DEBUG:usb.backend.libusb1:_LibUSB.release_interface(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>, 0)
2018-04-30 15:21:51,685 DEBUG:usb.backend.libusb1:_LibUSB.close_device(<usb.backend.libusb1._DeviceHandle object at 0x7f9df57f32b0>)
2018-04-30 15:21:51,687 DEBUG:usb.backend.libusb1:_LibUSB._finalize_object()
```

**Comment by domenzain** [comment]
Hi @WIsbrecht ,

Sorry for the delay. It seems the camera itself does not respond to the request.
I will have a look at Sony's extension to see if there is something essential missing.

Currently no extension is implemented in PTPy for Sony cameras.

Best,

**Comment by domenzain** [comment]
From 2d9e551, there is an ongoing implementation of the Sony extension.

**Comment by WIsbrecht** [comment]
Hey,

i did a quick single step debug session and found that the timeout error occurs even before 
https://github.com/Parrot-Developers/sequoia-ptpy/blob/db16f2699848bd0ba12ab1286e6d9c138b7b54a3/ptpy/__init__.py#L119
is called.
Actually the timeout occurs when this is called:
https://github.com/Parrot-Developers/sequoia-ptpy/blob/db16f2699848bd0ba12ab1286e6d9c138b7b54a3/ptpy/__init__.py#L116
An exception is thrown at this location:
https://github.com/Parrot-Developers/sequoia-ptpy/blob/db16f2699848bd0ba12ab1286e6d9c138b7b54a3/ptpy/transports/usb.py#L405-L415

**Comment by domenzain** [comment]
Hi,

The write transaction to get the camera details is timing out. It is ignored the first time, but the second time around it fails.

I've reduced the maximum transfer size in the latest master.
Could you give it a go?

Also, have you enabled the remote control in the options in the camera?

**Comment by WIsbrecht** [comment]
Hey,

just tried the latest master. No dice.
I can control the camera with gphoto2 though.
Could it be the udev rules which come with gphoto? Is there a way to actually make sure that ptpy can talk to my camera?

**Comment by domenzain** [comment]
Usually all it takes is to disable automatic volume mounting (or manually ejecting the camera volume before running your script).
But by the looks of it, it is not the camera being busy that fails but rather that it times out.

**Comment by domenzain** [comment]
Hi @WIsbrecht ,

I have a couple of Sony cameras at hand for testing.
There should be no issue in instantiating the camera.
Please try with the latest master and ensure the camera is not mounted.

FYI, the Ubuntu interface uses libgphoto2 so it might handle handing the camera back and forth. This is not the case for PTPy, it is fully independent.

A full implementation of the Sony extension is on the works.

Best,

**Comment by holistech** [comment]
Hi,
just an update regarding Sony camera support.
I have setup a raspberry pi 4 and my Sony a6000 camera. 
I tried the latest master branch of ptpy (28 December 2020).

Catching the device information with the example script print_device_info.py works fine:
https://pastebin.com/DJXAnnsq

However, i tried the trigger.py and the download_all_images.py scripts and got usb.core.USBError: [Errno 32] Pipe errors.
The debug output for trigger.py is available here:
https://pastebin.com/AJxES4kv

The debug output for download_all_images.py is available here:
https://pastebin.com/7g5GMyTz

I would love to use PTPy for my Sony camera project instead of gphoto2. 
What could be the reasons for the errors?

Best
