### ISSUE TITLE
No USB PTP device found

### ISSUE THREAD

**Issue by adelineh2000** [Parrot-Developers/sequoia-ptpy#30]
I want to use ptpy to communicate with my Sequoia.  When I plug the sequoia into my Mac via USB and run the example, `python ./trigger.py`, I get a `ptpy.ptp.PTPError`:

```
E 439 ptpy.transports.usb[MainThread:__available_cameras:119] No USB PTP device found.
E 440 ptpy.transports.usb[MainThread:__available_cameras:119] No USB PTP device found.
Traceback (most recent call last):
  File "./trigger.py", line 4, in <module>
    camera = ptpy.PTPy()
  File "/Users/adelinehillier/anaconda3/lib/python3.6/site-packages/ptpy/__init__.py", line 133, in __new__
    instance = PTPy(device=device)
  File "/Users/adelinehillier/anaconda3/lib/python3.6/site-packages/ptpy/ptp.py", line 712, in __init__
    super(PTP, self).__init__(*args, **kwargs)
  File "/Users/adelinehillier/anaconda3/lib/python3.6/site-packages/ptpy/transports/usb.py", line 92, in __init__
    self.__acquire_camera(devs)
  File "/Users/adelinehillier/anaconda3/lib/python3.6/site-packages/ptpy/transports/usb.py", line 125, in __acquire_camera
    for _ in self.__available_cameras(devs):
  File "/Users/adelinehillier/anaconda3/lib/python3.6/site-packages/ptpy/transports/usb.py", line 120, in __available_cameras
    raise PTPError(message)
ptpy.ptp.PTPError: No USB PTP device found.

```

When I use a Raspberry Pi instead, I get the same error. In both cases, the sequoia is not recognized as a USB device under lsusb. Ideas?

**Comment by domenzain** [comment]
For raspbian, if you're using the desktop environment it is likely that the camera auto-mounts as a drive.
This uses PTP behind the scenes and claims the device until it is unmounted.

If it looks like the camera is mounted on the file browser, unmount it and try again.

If that does not work, please show the output for `lsusb -v -d 19cf:` on your raspi with the camera connected (it lists all of Parrot's USB devices).
Be aware of the power requirements of the camera, it might be necessary to have a powered hub.

**Comment by ohbhatt** [comment]
I am getting the same error on a Windows 10 machine and a oneplus 6T in PTP mode. The phone is connected and unlocked. I also installed the libusb-32 drivers using zadig installer.

Is there anything else that I am missing? Please help.

**Comment by domenzain** [comment]
@ohbhatt, you will need to verify that the device in PTP/MTP mode has been assigned the libusb drivers. Android devices often change their USB PID depending on the mode they are in.

You can further check that the libusb driver is indeed in use through the Device Manager.

**Comment by ohbhatt** [comment]
Dear Mr.@domenzain, First of all, I would like to express my gratitude towards you and the team for developing such APIs and utilities for the community.

After I installed the driver, the device shows as a serial device and not under cameras or as some other PTP/MTP device, I have replaced the drivers with all the options from zadig installer, but none of them seems to work. Can you tell what the device should look like in the device manager?

**Comment by domenzain** [comment]
Hi @ohbhatt,

I've used the libUSBK driver in the past.
In that case the device should appear under "libusbK USB Devices", a category on the same level as keyboards.

In any case, you should make sure that it does not appear as a serial port.
