### ISSUE TITLE
BitField has gone in construct 2.8.x

### ISSUE THREAD

**Issue by peircej** [Parrot-Developers/sequoia-ptpy#7]
When I did `pip install ptpy` it wouldn't import:
```
>>> import ptpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptpy/__init__.py", line 3, in <module>
    from .extensions.canon import PTPDevice as canon
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptpy/extensions/canon.py", line 6, in <module>
    from .. import ptp
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ptpy/ptp.py", line 13, in <module>
    from construct import (
ImportError: cannot import name BitField
```

This appears to be due to a change in the 2.5-2.8 transition of construct:
https://github.com/construct/construct/blob/a5e76e247f23065596e321fd2dded8fe49e1b103/docs/transition.rst

**Comment by domenzain** [comment]
Indeed.

There are a few other things that need re-writing to use the new construct API. This is on the works but will take at least two more weeks complete.

**Comment by domenzain** [comment]
Since this is tracked somewhere else I'm closing this issue.

**Comment by peircej** [comment]
Ah yes. Apologies for the dup!
