### ISSUE TITLE
(Apple) iOS 10.2 compatibility

### ISSUE THREAD

**Issue by jcea** [Parrot-Developers/sequoia-ptpy#8]
Trying this with my iOS 10.2 device (iPhone 6, just updated), I see this error:

```
>>> from ptpy import PTPy
>>> camera = PTPy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ptpy/__init__.py", line 64, in __new__
    device_info = plain_camera.get_device_info()
  File "/usr/local/lib/python2.7/site-packages/ptpy/ptp.py", line 977, in get_device_info
    response = self.recv(ptp)
  File "/usr/local/lib/python2.7/site-packages/ptpy/transports/usb.py", line 342, in recv
    self.__send_request(ptp_container)
  File "/usr/local/lib/python2.7/site-packages/ptpy/transports/usb.py", line 320, in __send_request
    self.__send(ptp)
  File "/usr/local/lib/python2.7/site-packages/ptpy/transports/usb.py", line 295, in __send
    transaction = self.__CommandTransaction.build(ptp_container)
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 212, in build
    self.build_stream(obj, stream)
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 219, in build_stream
    self._build(obj, stream, Container())
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 290, in _build
    self.subcon._build(self._encode(obj, context), stream, context)
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 691, in _build
    sc._build(subobj, stream, context)
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 273, in _build
    self.subcon._build(obj, stream, context)
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 689, in _build
    subobj = obj[sc.name]
KeyError: 'OperationsSupported'
>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/ptpy/transports/usb.py", line 386, in __poll_events
    evt = self.__recv(event=True, wait=False, raw=True)
  File "/usr/local/lib/python2.7/site-packages/ptpy/transports/usb.py", line 274, in __recv
    usbdata[0:self.__Header.sizeof()]
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 188, in parse
    return self.parse_stream(BytesIO(data))
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 198, in parse_stream
    return self._parse(stream, Container())
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 670, in _parse
    subobj = sc._parse(stream, context)
  File "/usr/local/lib/python2.7/site-packages/construct/core.py", line 288, in _parse
    return self._decode(self.subcon._parse(stream, context), context)
  File "/usr/local/lib/python2.7/site-packages/construct/adapters.py", line 104, in _decode
    obj, self.subcon.name))
MappingError: no decoding mapping for 34817 [Type]
```

**Comment by domenzain** [comment]
It seems the USB packet type itself is not known, which probably means non-compliant behaviour from the iPhone. I have only just pushed some modifications which should help clear that up.

Could you please try `make test` from the project root when your iPhone is connected in PTP/MTP mode?

**Comment by jcea** [comment]
Checked out current master head. Running the test:

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.0.5, py-1.4.31, pluggy-0.4.0 -- /usr/local/bin/python
cachedir: .cache
rootdir: /tmp/sequoia-ptpy, inifile: pytest.ini
[Errno 5] Input/output error
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/tmp/sequoia-ptpy/ptpy/transports/usb.py", line 387, in __poll_events
    evt = self.__recv(event=True, wait=False, raw=True)
  File "/tmp/sequoia-ptpy/ptpy/transports/usb.py", line 273, in __recv
    raise e
USBError: [Errno 5] Input/output error

collected 58 items 

tests/hardware/test_camera.py::TestCamera::test_device_info SKIPPED
tests/hardware/test_captures.py::TestCamera::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_captures.py::TestCapture::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_captures.py::TestCapture::test_event_order SKIPPED
tests/hardware/test_captures.py::TestOpenCapture::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_captures.py::TestOpenCapture::test_termination SKIPPED
tests/hardware/test_compliance.py::TestCamera::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_compliance.py::TestCompliance::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_compliance.py::TestCompliance::test_PIMA_15740_2000_mandatory SKIPPED
tests/hardware/test_compliance.py::TestCompliance::test_ISO_15740_2013_mandatory SKIPPED
tests/hardware/test_compliance.py::TestCompliance::test_microsoft_windows_support SKIPPED
tests/hardware/test_properties_get_set_reset.py::TestCamera::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_properties_get_set_reset.py::TestGetSetResetProperties::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/test_properties_get_set_reset.py::TestGetSetResetProperties::test_get_set_property[device_property0] SKIPPED
tests/hardware/test_properties_get_set_reset.py::TestGetSetResetProperties::test_reset_property[device_property0] SKIPPED
tests/hardware/test_properties_get_set_reset.py::TestGetSetResetProperties::test_desc_get_property_identical[device_property0] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_keep_on SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_keep_on_capture SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[0] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[1] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[2] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[3] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[4] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[5] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[6] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[7] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[8] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[9] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[10] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[11] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[12] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[13] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[14] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[15] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[16] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[17] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[18] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[19] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[20] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[21] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[22] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[23] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[24] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[25] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[26] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[27] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[28] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[29] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[30] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_enable_capture[31] SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoiaEnableCapture::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/parrot/sequoia/test_enable_capture.py::TestSequoia::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/parrot/sequoia/test_operation_values.py::TestOperationValues::test_hotness SKIPPED
tests/hardware/parrot/sequoia/test_operation_values.py::TestOperationValues::test_absolute_zero SKIPPED
tests/hardware/parrot/sequoia/test_operation_values.py::TestOperationValues::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/parrot/sequoia/test_operation_values.py::TestSequoia::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/parrot/sequoia/test_sequoia.py::TestSequoia::test_device_info <- tests/hardware/test_camera.py SKIPPED
tests/hardware/parrot/sequoia/test_sequoia.py::TestCamera::test_device_info <- tests/hardware/test_camera.py SKIPPED
=========================== short test summary info ============================
SKIP [55] /tmp/sequoia-ptpy/tests/hardware/conftest.py:16: No camera available to test
SKIP [1] tests/hardware/test_properties_get_set_reset.py:21: got empty parameter set ['device_property'], function test_get_set_property at /tmp/sequoia-ptpy/tests/hardware/test_properties_get_set_reset.py:21
SKIP [1] tests/hardware/test_properties_get_set_reset.py:86: got empty parameter set ['device_property'], function test_desc_get_property_identical at /tmp/sequoia-ptpy/tests/hardware/test_properties_get_set_reset.py:86
SKIP [1] tests/hardware/test_properties_get_set_reset.py:71: got empty parameter set ['device_property'], function test_reset_property at /tmp/sequoia-ptpy/tests/hardware/test_properties_get_set_reset.py:71

========================== 58 skipped in 0.77 seconds ==========================
```
The phone is plugged and unlocked.

**Comment by jcea** [comment]
Any advance?.

Thanks!.

**Comment by domenzain** [comment]
Hey. The USB interface has become much more robust.

Sorry this has been around for so long.
Could you please have a look with the latest release/master?

You can set the environment variable `PTPY_DEBUG` to produce logs.

**Comment by domenzain** [comment]
I'm closing this. Please re-open if issue is still there.

Thanks!
